import {scoreEffects, bestSkillTarget} from './tactical-ai.mjs';
/* global structuredClone */
// Actual card/hand/resource interpreter. Base damage/status physics are supplied by the battle kernel.
export const COMMON_VERSION='2026-09-07.1';
export const supportAudit={conditions:new Set(),utilities:new Set(),kinds:new Set(),unknown:[]};
export const clone=x=>structuredClone(x);
export const clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
export const stat=(g,a,k)=>g.stat?g.stat(a,k):a.stats[k]||0;
export const alive=a=>a&&a.hp>0;
export const pets=g=>(g.allies||[]).filter(a=>alive(a)&&a.isSummon);
export const allBad=a=>[...(a.debuffs||[]),...(a.dots||[])];
const aliases={burn:['灼烧','burn'],poison:['中毒','poison'],bleed:['流血','bleed'],curse:['蚀魂','诅咒','curse'],weak:['虚弱','weak'],wet:['湿润','wet'],vulnerable:['易伤','vulnerable'],taunt:['嘲讽','taunt'],freeze:['冻结','freeze'],hard_control:['冻结','眩晕','强控','束缚','光缚','影缚','沉眠','麻痹','hard_control']};
export function has(a,name){const wanted=aliases[name]||[name];return [...(a?.buffs||[]),...allBad(a||{})].some(e=>wanted.some(s=>String(e.canonicalStatus||e.status||e.name||'').includes(s)||String(e.status||'').includes(s)));}
export const badTypes=a=>new Set(allBad(a).map(e=>e.canonicalStatus||e.status)).size;
export function shuffled(a,rng){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
const limitsText=c=>Array.isArray(c.limits)?c.limits.join('；'):c.limits||'';
const isBlank=c=>c.id==='mg_blank_card';
const restricted=c=>c.ap===0||c.effects.some(e=>['draw','resource','retrieve','scry_draw','discard','summon','chant'].includes(e.kind)||e.consume||e.perResource||e.action&&/draw|discover|recover|copy|discard|resource|检索|抽牌|回收|复制|弃牌/.test(e.action));
const specialBuff=e=>Boolean(e.charges||e.chargesPerSummon||/下张|下一|本卡|变招|同名连击|兵器|血月猎杀|反击/.test(e.status||''));
const isCost=e=>e.preResolve===true||e.phase==='preResolve'||e.kind==='hp_cost'||e.kind==='resource'&&(e.consume||typeof e.amount==='string'||Number(e.amount)<0)||e.kind==='discard'&&e.cost||e.kind==='utility'&&['self_cost','destroy_summon','remove_blank','consume_all_resource'].includes(e.action);
const resourceName=s=>String(s).toUpperCase()==='AP'?'AP':s;
const hpRatio=e=>e.maxHp??e.maxHpRatio??((e.maxHpPercent||0)/100);
const gather=(es,out=[])=>{for(const e of es){out.push(e);for(const k of ['options','effects','entry'])if(Array.isArray(e[k]))gather(e[k],out);for(const s of e.skills||[])gather(s.effects,out);}return out;};
function state(g){return g.player.flags.pc;}
function log(g,type,detail){g.log?.(type,detail);}
function unknown(where,value){supportAudit.unknown.push({where,value});throw new Error(`UNSUPPORTED_PLAYER_${where}: ${typeof value==='string'?value:JSON.stringify(value)}`);}
function targets(g,e,source,target){if(e.lockedTargetId)return g.allies.filter(a=>alive(a)&&a.id===e.lockedTargetId);if(e.target==='all_enemies')return (g.livingEnemies?g.livingEnemies():g.enemies.filter(alive));if(e.target==='all_allies')return (g.livingAllies?g.livingAllies():g.allies.filter(alive));if(e.target==='owner')return [g.player];if(e.target==='self'||!e.target&&['heal','shield','buff'].includes(e.kind))return[source];if(e.target==='ally'&&g.selectedAllyId){const selected=g.allies.find(a=>alive(a)&&a.id===g.selectedAllyId);if(selected)return[selected];}if(e.target==='ally')return[g.allies.filter(alive).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp||String(a.id).localeCompare(String(b.id)))[0]||source];return[alive(target)?target:g.enemies.find(alive)].filter(Boolean);}
export function createPlayerController(hooks={}){
 const ctrl={};
 function makeContext(g,card={id:'__phase',ap:0,effects:[]},target=g.enemies.find(alive)){
  const p=g.player,ctx={g,p,card,target,printedAP:card.ap||0,paidAP:0,spent:{},results:[],totals:{damage:0,hpDamage:0,shieldDamage:0,heal:0,overheal:0,shield:0,cleanses:0,dispels:0,debuffs:0,dot:0,kills:0,selfDamage:0,draw:0,summoned:0,removedSummons:0},before:{hp:p.hp,shield:p.shield,targetHp:target?.hp||0,targetShield:target?.shield||0,targetDebuffs:badTypes(target||{}),targetBuffs:(target?.buffs||[]).length},effects:clone(card.effects||[]),directBonus:0,damageAdd:{flat:0,atk:0},options:{},hitTargets:new Map(),source:p};
  ctx.resolve=(e,t=ctx.target,source=ctx.source)=>resolve(ctx,e,t,source);
  ctx.damage=(e,t=ctx.target,source=ctx.source)=>resolve(ctx,{kind:'damage',hits:1,crit:true,target:'enemy',...e},t,source);
  ctx.draw=n=>draw(g,n,true,ctx);
  ctx.resource=(name,delta)=>resource(ctx,name,delta);
  ctx.cleanse=(target=ctx.p,n=1,specific)=>cleanse(ctx,target,n,specific);
  ctx.summon=e=>summon(ctx,e);
  ctx.removeSummons=(n,filter)=>removeSummons(ctx,n,filter);
  ctx.condition=t=>condition(t,ctx);
  ctx.stat=(a,key)=>stat(g,a,key);
  return ctx;
 }
 function noteResult(ctx,r,e,target){if(!r)return;r=typeof r==='number'?{[e.kind]:r}:r;ctx.results.push({effect:e,targetId:target?.id,...r});for(const k of ['damage','hpDamage','shieldDamage','heal','shield','dot'])ctx.totals[k]+=Number(r[k]||0);ctx.totals.debuffs+=Number(r.debuffs??r.debuff??0);ctx.totals.cleanses+=Number(r.cleanse||0);ctx.totals.dispels+=Number(r.dispel||0);if(r.hit!==undefined&&e.kind==='damage')ctx.hitTargets.set(target.id,r.hit);return r;}
 function condition(text,ctx){if(!text)return true;supportAudit.conditions.add(text);const custom=hooks.condition?.(text,ctx);if(custom!==undefined)return !!custom;const {g,p,target:t}=ctx;switch(text){
 case'自身无负面状态':return allBad(p).length===0;case'自身有护盾':case'当前有护盾':return p.shield>0;
 case'实际净化至少1个状态':return ctx.totals.cleanses>0;case'目标有负面状态':return allBad(t||{}).length>0;
 case'本卡直接攻击命中':case'直击命中':case'对应目标直击命中':return ctx.hitTargets.get(t?.id)===true;
 case'目标无护盾':return !(t?.shield>0);case'目标出牌前有护盾':return ctx.before.targetShield>0;
 case'陷阱触发':case'地雷触发':return !!ctx.triggered;
 case'目标生命不超过30%且有负面状态':return t.hp/t.maxHp<=.3&&allBad(t).length>0;
 case'目标有深渊或龙标签':return /abyss|dragon|深渊|龙/.test(JSON.stringify(t.tags||t.source?.tags||[]));
 case'目标已有中毒':return has(t,'poison');case'目标已有灼烧':return has(t,'burn');
 case'实际移除中毒':return (ctx.removedStatuses||[]).some(z=>/poison|中毒/.test(z));
 case'消耗1零件':if((p.resources['零件']||0)<1)return false;if(!ctx.preview)resource(ctx,'零件',-1);return true;
 case'目标有不死或深渊标签':return /undead|abyss|不死|深渊/.test(JSON.stringify(t.tags||[]));
 case'自身HP低于50%':return p.hp/p.maxHp<.5;case'自身HP<35%，在本牌治疗前检查':return ctx.before.hp/p.maxHp<.35;
 case'实际驱散增益':return ctx.totals.dispels>0;case'本回合支付过生命':return state(g).selfPaid>0;
 case'本回合支付过生命且直击命中':return state(g).selfPaid>0&&ctx.hitTargets.get(t?.id)===true;
 case'目标为吸血鬼或不死':case'对应目标为吸血鬼或不死':return /vampire|undead|吸血鬼|不死/.test(JSON.stringify(t.tags||[]));
 case'处于血月猎杀':return has(p,'血月猎杀');case'前一张打出的是同名牌':return state(g).lastCard===ctx.card.id;
 case'本卡成功施加中毒':return ctx.totals.dot>0;
 default:return unknown('CONDITION',text);
 }}
 function draw(g,n,extra=true,ctx){const p=g.player,s=state(g),limit=p.handLimit||10;if(extra)n=Math.min(n,6-s.extraDraw);let got=0;while(n-->0&&p.hand.length<limit){if(!p.deck.length){if(!p.discard.length)break;p.deck=shuffled(p.discard,g.rng);p.discard=[];}const c=p.deck.shift();if(!c)break;p.hand.push(c);got++;}if(extra)s.extraDraw+=got;if(ctx)ctx.totals.draw+=got;log(g,'draw',{extra,count:got,hand:p.hand.length});return got;}
 function resource(ctx,name,delta){const {g,p}=ctx,s=state(g);name=resourceName(name);if(name==='AP'){if(delta<0){if(p.ap<-delta)throw Error('insufficient AP');p.ap+=delta;}else{const gain=Math.min(delta,3-s.extraAP);p.ap+=gain;s.extraAP+=gain;delta=gain;}}else{const cap=p.resourceCaps?.[name]??s.resourceCaps[name]??100,roundCap=s.resourceRoundCaps[name]??Infinity;let cur=p.resources[name]||0;if(delta<0){if(cur+delta<0)throw Error(`insufficient resource ${name}`);p.resources[name]=cur+delta;ctx.spent[name]=(ctx.spent[name]||0)-delta;}else{delta=Math.min(delta,cap-cur,roundCap-(s.gained[name]||0));delta=Math.max(0,delta);p.resources[name]=cur+delta;s.gained[name]=(s.gained[name]||0)+delta;}}ctx.results.push({kind:'resource',resource:name,delta});return delta;}
 function cleanse(ctx,target,n,specific){const before=allBad(target).map(e=>e.canonicalStatus||e.status);let removed=0;if(specific){for(const key of ['debuffs','dots']){const a=target[key]||[];target[key]=a.filter(e=>{const match=(aliases[specific]||[specific]).some(t=>String(e.canonicalStatus||e.status).includes(t)||String(e.status).includes(t));if(match&&removed<(n==='all'?Infinity:n)){removed++;return false;}return true;});}}else if(ctx.g.cleanse)removed=ctx.g.cleanse(target,n);else{const count=n==='all'?Infinity:n;for(const key of ['debuffs','dots'])while((target[key]||[]).length&&removed<count){target[key].shift();removed++;}}ctx.totals.cleanses+=removed;ctx.removedStatuses=(ctx.removedStatuses||[]).concat(before.filter(x=>!allBad(target).some(e=>(e.canonicalStatus||e.status)===x)));ctx.results.push({kind:'cleanse',targetId:target.id,count:removed});return removed;}
 function dispel(ctx,target,n){const got=ctx.g.dispel?ctx.g.dispel(target,n):0;ctx.totals.dispels+=got;ctx.results.push({kind:'dispel',count:got});return got;}
 function resourceEffect(ctx,e){const name=e.resource;let n=e.amount??e.value??0;if(typeof n==='string'){const have=ctx.p.resources[name]||0;if(have<(e.requiredMin||0))throw Error('resource min');n=-Math.min(have,e.maxConsume??have);}else if(e.consume)n=-Math.abs(n);return resource(ctx,name,n);}
 function handCandidates(ctx,e={}){return ctx.p.hand.filter(c=>c.uid!==ctx.card.uid&&!isBlank(c)&&!(e.exclude&&/资源|resource|非资源/.test(String(e.exclude))&&gather(c.effects).some(z=>z.kind==='resource'))&&!(e.cost&&c.generated));}
 function flyingCandidates(ctx){let a=handCandidates(ctx),keep=new Set();if(ctx.g.options?.patch?.smartFlying){const ap=ctx.p.ap-(ctx.paidAP>0?0:price(ctx.g,ctx.card));if(ctx.p.shield<(ctx.g.expectedIncoming||0)){const guards=a.filter(c=>c.ap<=ap&&gather(c.effects).some(e=>e.kind==='shield')).sort((a,b)=>a.ap-b.ap);if(guards[0])keep.add(guards[0].uid);}const draw=a.filter(c=>c.ap<=ap&&gather(c.effects).some(e=>e.kind==='draw'||e.kind==='scry_draw')).sort((a,b)=>a.ap-b.ap);if(draw[0])keep.add(draw[0].uid);}return a.filter(c=>!keep.has(c.uid));}
 function discardCards(ctx,e){let a=ctx.card.id==='mg_flying_cards'&&ctx.g.options?.patch?.smartFlying?flyingCandidates(ctx):handCandidates(ctx,e),n=Math.min(e.amount??e.max??1,a.length);if(e.max)n=Math.min(e.max,a.length);if(n<(e.min??e.amount??0))throw Error('insufficient discard');a.sort((a,b)=>scoreCard(ctx.g,a,ctx.target)-scoreCard(ctx.g,b,ctx.target));if(ctx.g.choose){a=ctx.g.choose('选择弃置的卡牌',a,n,e.max?e.min??1:n);n=a.length;}for(const c of a.slice(0,n)){ctx.p.hand.splice(ctx.p.hand.indexOf(c),1);ctx.p.discard.push(c);}ctx.discarded=(ctx.discarded||0)+n;ctx.results.push({kind:'discard',count:n});return n;}
 function removeSummons(ctx,n,filter){let a=pets(ctx.g).filter(a=>filter!=='mechanical'||a.mechanical).sort((a,b)=>(a.expiresRound||999)-(b.expiresRound||999)||a.hp-b.hp);const count=Math.min(n==='all'?a.length:n??1,a.length);for(const p of a.slice(0,count)){p.hp=0;p.removedByPlayer=true;}ctx.removedSummons=(ctx.removedSummons||0)+count;ctx.totals.removedSummons+=count;ctx.results.push({kind:'remove_summon',count});return count;}
 function summon(ctx,e){const {g,p}=ctx,s=state(g);let occupied=g.allies.filter(a=>alive(a)&&(a.isSummon||a.legacySummon)),slot=[0,1].find(x=>!occupied.some(a=>a.slot===x));if(slot===undefined){const old=occupied.sort((a,b)=>a.expiresRound-b.expiresRound||a.hp-b.hp)[0];slot=old.slot;old.hp=0;old.removedByPlayer=true;ctx.totals.removedSummons++;}const inh=e.inherit||{hp:e.hpRatio,atk:e.atkRatio,def:e.defRatio,speed:e.speedRatio??1,crit:e.critRatio??1,critDamage:e.critDamageRatio??1,effectHit:e.effectHitRatio??1,effectRes:e.resistanceRatio??1};const a={id:`${p.id}:pet:${++s.uid}`,side:'player',isSummon:true,ownerId:p.id,summonName:e.name,name:e.name,slot,flags:{},bornRound:g.round,expiresRound:g.round+(e.turns||3),skills:clone(e.skills||[]),summonDefinition:clone(e),mechanical:e.mechanical??(ctx.card.profession==='mechanic'||ctx.card.profession==='blacksmith'),level:p.level,hp:Math.max(1,p.maxHp*(inh.hp??.3)),maxHp:Math.max(1,p.maxHp*(inh.hp??.3)),shield:0,stats:{attack:stat(g,p,'attack')*(inh.atk??1),defense:stat(g,p,'defense')*(inh.def??.5),speed:stat(g,p,'speed')*(inh.speed??1),crit:stat(g,p,'crit')*(inh.crit??0),critDamage:stat(g,p,'critDamage')*(inh.critDamage??1),ehr:stat(g,p,'ehr')*(inh.effectHit??1),res:stat(g,p,'res')*(inh.effectRes??1)},buffs:[],debuffs:[],dots:[],resources:{},star:ctx.card.star||p.star||1};g.allies.push(a);ctx.totals.summoned++;ctx.results.push({kind:'summon',id:a.id,name:e.name});if(e.entry)for(const effect of e.entry)resolve(ctx,effect,a,a);return a;}
 function utility(ctx,e){supportAudit.utilities.add(e.action||e.kind);if(hooks.utility?.(e,ctx)===true)return true;const {g,p}=ctx,s=state(g);switch(e.action||e.kind){
 case'cleanse':case'净化':return cleanse(ctx,e.target==='all_allies'?p:targets(g,e,p,ctx.target)[0]||p,e.amount??1),true;
 case'cleanse_specific':case'净化特定状态':return cleanse(ctx,p,e.amount??1,e.status),true;
 case'dispel':return dispel(ctx,ctx.target,e.amount??1),true;
 case'self_cost':case'自损生命':case'hp_cost':{const n=p.maxHp*hpRatio(e);if(p.hp-n<1)throw Error('lethal player cost');p.hp-=n;s.selfPaid+=n;ctx.totals.selfDamage+=n;return true;}
 case'choose_one':{const option=g.choose?g.choose('选择效果',e.options,1)[0]:e.options.slice().sort((a,b)=>estimateEffect(ctx,b)-estimateEffect(ctx,a))[0];resolve(ctx,option);return true;}
 case'shield_damage':case'破盾附加伤害':{const t=ctx.target,n=e.shieldOnly?Math.min((t.shield||0)*(e.enemyShieldRatio??0),stat(g,p,'attack')*(e.capAtk||0)):(e.flat||0)+(e.atk||0)*stat(g,p,'attack');const loss=Math.min(t.shield||0,n*(ctx.card.star===3?1.2:ctx.card.star===2?1.1:1));t.shield-=loss;ctx.totals.shieldDamage+=loss;ctx.totals.damage+=loss;return true;}
 case'ap_discount':s.discounts.push({value:e.value??e.amount,charges:e.charges||1,minAp:e.minAp??1,filter:e.filter,expires:g.round});return true;
 case'consume_all_resource':{const got=Math.min(p.resources[e.resource]||0,e.max??Infinity);if(got<(e.min||0))throw Error('minimum resource');resource(ctx,e.resource,-got);return true;}
 case'discard':case'弃牌':discardCards(ctx,e);return true;
 case'destroy_summon':case'献祭召唤':case'召回召唤':removeSummons(ctx,e.amount||1,e.filter);return true;
 case'recover_card':case'回收弃牌':case'retrieve':{let pool=p.discard.filter(c=>!gather(c.effects).some(z=>z.kind==='resource'||z.action&&/回收|copy|复制/.test(z.action)));if(e.filter&&/mechanical|召唤/.test(e.filter))pool=pool.filter(c=>c.type==='summon');if(e.filter&&/水系/.test(e.filter))pool=pool.filter(c=>c.profession==='water_mage');const c=g.choose&&pool.length?g.choose('选择回收的卡牌',pool,1)[0]:pool.sort((a,b)=>scoreCard(g,b,ctx.target)-scoreCard(g,a,ctx.target))[0];if(c){p.discard.splice(p.discard.indexOf(c),1);if(e.kind==='retrieve')p.deck.unshift(c);else if(p.hand.length<(p.handLimit||10))p.hand.push(c);else p.discard.push(c);}return true;}
 case'scry_draw':{let choices=[];for(let i=0;i<e.look;i++){if(!p.deck.length&&p.discard.length){p.deck=shuffled(p.discard,g.rng);p.discard=[];}if(p.deck.length)choices.push(p.deck.shift());}choices.sort((a,b)=>scoreCard(g,b,ctx.target)-scoreCard(g,a,ctx.target));const n=Math.min(e.draw,6-s.extraDraw,(p.handLimit||10)-p.hand.length);const selected=g.choose&&n>0?g.choose('选择抽取的卡牌',choices,n):choices.slice(0,n);p.hand.push(...selected);p.deck.push(...choices.filter(c=>!selected.includes(c)));s.extraDraw+=n;ctx.totals.draw+=n;return true;}
 case'next_attack_flat':s.nextAttackFlat={flat:e.flat,atk:e.atk,expires:g.round,charges:e.charges||1};return true;
 case'shield_conversion':{const sf=1+.1*((ctx.card.star||p.star||1)-1),n=Math.min(p.shield*(e.ratio||.5),((e.flatCap||0)+(e.atkCap||0)*stat(g,p,'attack'))*sf);p.shield-=n;ctx.damageAdd.flat+=n/sf;return true;}
 case'enemy_shield_bonus':{const sf=1+.1*((ctx.card.star||p.star||1)-1);ctx.damageAdd.flat+=Math.min(ctx.before.targetShield*e.ratio,(e.flatCap+e.atkCap*stat(g,p,'attack'))*sf)/sf;return true;}
 case'exhaust':ctx.exhaust=true;return true;
 case'generate_blank':return generateBlank(ctx,e.value||1),true;
 case'blank_regen':s.blankRegen={remaining:e.ticks||3,next:g.round+1};return true;
 case'remove_blank':{const a=p.hand.filter(isBlank).slice(0,e.max||8);if(a.length<(e.min||1))throw Error('missing blank');for(const c of a)p.hand.splice(p.hand.indexOf(c),1);ctx.removedBlanks=a.length;return true;}
 case'unplayable':return true;
 case'discover':return discover(ctx,e),true;
 case'bribe':g.outcome='bribed';return true;
 case'escape_after_enemy_phase':s.escapePending=true;return true;
 case'群攻总量上限':ctx.caps??={};ctx.caps.damage={flat:e.flat,atk:e.atk};return true;
 case'群体DOT总倍率上限':ctx.caps??={};ctx.caps.dot={flat:0,atk:e.atkPerTick};return true;
 case'群体治疗总量上限':ctx.caps??={};ctx.caps.heal={flat:e.flat,atk:e.atk};return true;
 case'群体再生总量上限':ctx.caps??={};ctx.caps.heal={flat:e.flatPerTick,atk:e.atkPerTick};return true;
 case'群体恢复总量上限':case'群体总量上限':ctx.caps??={};for(const k of ['damage','heal','shield'])if(e[k])ctx.caps[k]=e[k];return true;
 default:if(!e.action&&e.text==='否则净化自己1个负面状态'){if(allBad(p).length)cleanse(ctx,p,1);return true;}return unknown('UTILITY',e);
 }}
 function generateBlank(ctx,n){const {p,g}=ctx,s=state(g);let have=[...p.hand,...p.deck,...p.discard].filter(isBlank).length;const template=s.catalog.get('mg_blank_card')||{id:'mg_blank_card',name:'空白牌',ap:0,effects:[{kind:'utility',action:'unplayable'}]};while(n-->0&&have++<8){const c={...template,uid:++s.uid,generated:true,star:1};p.deck.splice(Math.floor(g.rng()*(p.deck.length+1)),0,c);}}
 function discover(ctx,e){const {p,g}=ctx,s=state(g);let candidates=s.discoveryPool||[];if(!candidates.length)throw Error('empty safe discovery pool');if(!s.discoveryQueue?.length)s.discoveryQueue=shuffled(candidates,g.rng);let list=[];while(list.length<e.reveal&&s.discoveryQueue.length)list.push(s.discoveryQueue.shift());list.sort((a,b)=>scoreCard(g,b,ctx.target)-scoreCard(g,a,ctx.target));const n=Math.min(e.pick,12-s.generatedDiscovery,(p.handLimit||10)-p.hand.length);const selected=g.choose&&n>0?g.choose('星象发现：选择卡牌',list,n):list.slice(0,n);for(const c of selected){p.hand.push({...c,uid:++s.uid,generated:true,discovered:true,star:1});s.generatedDiscovery++;}s.discoveryQueue.push(...list);s.discoveriesThisTurn++;ctx.results.push({kind:'discover',count:n});}
 function resolve(ctx,raw,target=ctx.target,source=ctx.source){const oldTarget=ctx.target,oldSource=ctx.source;try{return resolveImpl(ctx,raw,target,source);}finally{ctx.target=oldTarget;ctx.source=oldSource;}}
 function resolveImpl(ctx,raw,target=ctx.target,source=ctx.source){const {g,p}=ctx,s=state(g);let e=clone(raw);supportAudit.kinds.add(e.kind);const local=ctx;local.target=target;local.source=source;if(e.condition&&/陷阱触发|地雷触发/.test(e.condition)&&ctx.activeTrigger&&!ctx.triggered){ctx.activeTrigger.effects.push({...e,condition:undefined});return;}
 if(e.condition&&!["all_enemies","all_allies"].includes(e.target)&&!condition(e.condition,local))return;
 if(hooks.effect?.(e,local)===true)return;
 if(e.kind==='buff'&&e.effects&&e.trigger&&!ctx.triggered){s.triggers=s.triggers.filter(t=>t.id!==ctx.card.id+':'+source.id);s.triggers.push({id:ctx.card.id+':'+source.id,kind:'afterIncomingDamage',sourceId:source.id,expires:g.round+(e.turns||1),remaining:Infinity,perRound:e.maxTriggersPerRound||1,effects:e.effects,card:ctx.card});delete e.trigger;}
 if(e.trigger&&!ctx.triggered){const trigger={id:`${ctx.card.id}:${target?.id}`,kind:/攻击前|行动前|技能前/.test(e.trigger)?'beforeEnemyAction':'afterIncomingDamage',sourceId:source.id,targetId:target?.id,expires:g.round+(/陷阱|地雷|伏击/.test(ctx.card.name||'')?2:1),remaining:1,effects:[{...e,trigger:undefined}],card:ctx.card};s.triggers=s.triggers.filter(t=>t.id!==trigger.id);s.triggers.push(trigger);ctx.activeTrigger=trigger;return;}
 if(['utility','cleanse','dispel','discard','retrieve','scry_draw','hp_cost','exhaust'].includes(e.kind))return utility(local,e);
 if(e.kind==='draw')return draw(g,Number(e.value??e.amount),true,ctx);
 if(e.kind==='resource')return resourceEffect(ctx,e);
 if(e.kind==='summon')return summon(ctx,e);
 if(e.kind==='conditional'){for(const child of e.effects||[])resolve(ctx,child,target,source);return;}
 if(e.kind==='chant')return unknown('KIND',e);
 if(!['damage','heal','shield','dot','debuff','buff'].includes(e.kind))return unknown('KIND',e);
 if(e.kind==='heal'&&(e.ticks||e.overTime)&&!ctx.scheduled){const dests=targets(g,e,source,target),scale=dests.length>2?2/dests.length:1;for(const dest of dests){const key=ctx.card.id+':'+source.id+':'+dest.id;const raw=g.calcBase?g.calcBase(source,dest,e,{star:ctx.card.star||p.star||1,scale}):((e.flat||0)+(e.atk||0)*stat(g,source,'attack'))*scale;const n=raw*(1+(g.statusRatio?.(source,'治疗量增加')||0)+(g.statusRatio?.(source,'治疗与护盾提高%')||0));const snapshot={...source,stats:{...source.stats},flags:{},buffs:[],debuffs:[],dots:[],resources:{}};s.regens=s.regens.filter(z=>z.key!==key);s.regens.push({key,group:(e.status||'再生')+':'+dest.id,effect:{kind:'heal',flat:n,atk:0,target:'ally',lockedTargetId:dest.id},remaining:e.ticks||e.overTime,next:g.round+1,sourceId:source.id,targetId:dest.id,snapshot,card:{...ctx.card,star:1}});}return;}
 if(e.kind==='buff'&&e.effects&&e.trigger){s.triggers.push({id:ctx.card.id+':'+source.id,kind:'afterIncomingDamage',sourceId:source.id,expires:g.round+(e.turns||1),remaining:Infinity,perRound:e.maxTriggersPerRound||1,effects:e.effects,card:ctx.card});}
 if(e.kind==='buff'&&e.preResolve&&/本卡|下张|下一/.test(e.status||'')){const value=e.valueUnit==='ratio'||Math.abs(e.value)<1?e.value:e.value/100;ctx.directBonus+=value;return;}
 if(e.kind==='buff'&&typeof e.perResource==='number'){const n=ctx.spent['理智']||0;e.value=Math.min(e.maxValue??1,Math.floor(n/e.perResource)*e.value);}
 let mult=1;
 if(e.perResource&&typeof e.perResource==='string')mult=ctx.spent[e.perResource]||0;
 if(e.perDebuffType)mult=Math.min(e.max||3,badTypes(target));
 if(e.perDestroyedSummon)mult=Math.min(e.max||2,ctx.removedSummons||ctx.totals.removedSummons);
 if(e.perDiscardedCard)mult=Math.min(e.max||4,ctx.discarded||0);
 if(e.perRemovedBlank)mult=Math.min(e.max||8,ctx.removedBlanks||0);
 if(e.perDispelledBuff)mult=Math.min(e.max||2,ctx.totals.dispels);
 if(e.perCleansedDebuff)mult=Math.min(e.max||3,ctx.totals.cleanses);
 if(mult===0)return;e.flat=(e.flat||0)*mult;e.atk=(e.atk||0)*mult;if(e.def!==undefined)e.def*=mult;
 if(e.kind==='damage'&&!e.mergeWithFirst&&!ctx.damageAddUsed){e.flat+=ctx.damageAdd.flat||0;e.atk+=ctx.damageAdd.atk||0;ctx.damageAddUsed=true;}
 const ts=targets(g,e,source,target);let scale=ts.length>2?2/ts.length:1;
 const cap=e.totalCap||ctx.caps?.[e.kind];if(cap&&ts.length){const budget=(e.flat||0)+(e.atk||0)*stat(g,source,'attack')+(e.def||0)*stat(g,source,'defense');const max=(cap.flat||0)+(cap.atk||0)*stat(g,source,'attack')+(cap.def||0)*stat(g,source,'defense');if(budget>0)scale=Math.min(scale,max/(budget*ts.length));}
 let out;for(const t of ts){if(!alive(t))continue;if(e.condition&&["all_enemies","all_allies"].includes(e.target)&&!condition(e.condition,{...ctx,target:t}))continue;const ee={...e,target:t.side==='enemy'?'enemy':t===(ctx.options.snapshotSource||source)?'self':'ally'};if(e.kind==='shield'&&t===p&&p.profession==='holy_knight'){for(const k of ['flat','atk','def'])if(ee[k])ee[k]*=1.2;}delete ee.condition;delete ee.ticks;delete ee.trigger;delete ee.preResolve;delete ee.phase;let bonus=ctx.directBonus||0;
 if(e.conditionBonus){if(e.conditionBonus==='目标HP<30%时直接增伤+15%'){if(t.hp/t.maxHp<.3)bonus+=.15;}else unknown('CONDITION_BONUS',e.conditionBonus);}
 const opts={star:ctx.card.star||source.star||p.star||1,scale,directBonus:bonus,...ctx.options,forceTarget:true};if(source.id!==p.id)opts.directBonus=0;
 const hpBefore=t.hp;let actualOverflow=0;out=noteResult(ctx,g.applyEffects([ee],ctx.options.snapshotSource||source,t,opts),ee,t);if(e.kind==='heal'){actualOverflow=g.lastHealResult?.overflow??0;ctx.totals.overheal+=actualOverflow;}if(e.kind==='heal'&&e.overflowToShield&&actualOverflow>0){const amount=Math.min(actualOverflow*e.overflowToShield,t.maxHp*(e.overflowCapMaxHp??.2));const up=1+(g.statusRatio?.(source,'治疗与护盾提高%')||0),got=g.shield(source,t,{kind:'shield',flat:amount/up,atk:0,def:0},{star:1});ctx.totals.shield+=got;ctx.results.push({kind:'overflow_shield',targetId:t.id,shield:got});}if(hpBefore>0&&t.hp<=0)ctx.totals.kills++;
 }return out;
 }
 function availableCost(ctx,e){const {p,g}=ctx;if(e.condition){try{if(!condition(e.condition,{...ctx,preview:true}))return true;}catch{/* Optional status helper: fall back to the stored status list. */}}
 if(e.kind==='resource'){const key=resourceName(e.resource),have=key==='AP'?p.ap:p.resources[key]||0;let n=e.amount??e.value??0;if(e.consume)n=-Math.abs(n);if(typeof n==='string')return have>=(e.requiredMin||0);return n>=0||have>=-n;}
 if(e.kind==='damage'&&e.consume)return (p.resources[e.perResource]||0)>=(e.min||1);
 if(e.kind==='hp_cost'||e.action==='self_cost'||e.action==='自损生命')return p.hp-p.maxHp*hpRatio(e)>=1;
 if(e.action==='consume_all_resource')return (p.resources[e.resource]||0)>=(e.min||0);
 if(e.kind==='discard'||e.action==='discard'||e.action==='弃牌')return handCandidates(ctx,e).length>=(e.min??e.amount??1);
 if(e.action==='remove_blank')return p.hand.filter(isBlank).length>=(e.min||1);
 if(['destroy_summon','献祭召唤','召回召唤'].includes(e.action))return pets(g).filter(p=>e.filter!=='mechanical'||p.mechanical).length>0;
 if(e.action==='discover')return state(g).discoveriesThisTurn<2&&state(g).generatedDiscovery<12;
 if(e.action==='bribe')return g.allowEscape===true&&g.enemies.every(e=>e.tier==='normal')&&(p.gold||0)>=(g.encounterGoldReward||100)*1.5;
 if(e.action==='escape_after_enemy_phase')return g.allowEscape===true&&!g.enemies.some(e=>e.tier==='boss'||e.locked);
 if(e.action==='unplayable')return false;return true;
 }
 function price(g,card,commit=false,target=g.enemies.find(alive)){const p=g.player,s=state(g);let ap=card.ap||0;if(card.noDiscountRound===g.round)return ap;for(const d of s.discounts){if(d.charges>0&&d.expires>=g.round&&(!d.filter||(d.filter==='wind_direct'?card.profession==='wind_mage'&&card.ap>=2&&card.effects.some(e=>e.kind==='damage'):d.filter.includes('summon')?card.ap>=2&&card.effects.some(e=>e.kind==='summon'):true))){const off=Math.min(d.value,Math.max(0,ap-(d.minAp??1)),3-s.extraAP);ap-=off;if(commit&&off>0){d.charges--;s.extraAP+=off;}break;}}const silence=card.type==='spell'?(p.debuffs||[]).find(e=>(e.canonicalStatus==='silence'||/沉默|禁言|silence/.test(e.status||''))&&(e.charges??1)>0):null;if(silence){ap++;if(commit)silence.charges=(silence.charges??1)-1;}const custom=hooks.adjustCost?.(card,makeContext(g,card,target),ap,commit);ap=Math.max(0,Number.isFinite(custom)?custom:ap);const override=g.cardCostOverride;
 if(override&&String(card.uid)===override.instanceId){const desired=Math.max(0,override.cost),discount=Math.min(Math.max(0,ap-desired),Math.max(0,3-s.extraAP));if(commit)s.extraAP+=discount;ap=desired>=ap?desired:ap-discount;}
 return ap;}
 function resolveCardTarget(g,card,target){return card.effects.some(e=>['damage','dot','debuff','dispel'].includes(e.kind)&&e.target==='enemy'&&!e.ignoreTaunt)?g.enemies.find(e=>alive(e)&&has(e,'taunt'))||target:target;}
 function canPlay(g,card,target=g.enemies.find(alive)){target=resolveCardTarget(g,card,target);const p=g.player,s=state(g),ctx=makeContext(g,card,target);ctx.preview=true;ctx.paidAP=price(g,card,false,target);if(!alive(p)||isBlank(card)||p.ap<ctx.paidAP)return false;if(restricted(card)&&s.used[card.uid||card.id]===g.round)return false;const txt=limitsText(card),uses=s.battleUses[card.id]||0;if(/每战最多2次|本战最多2次/.test(txt)&&uses>=2)return false;if(/每战最多1次|本战最多1次|每场最多1次/.test(txt)&&uses>=1)return false;if(/同名最多1次|同名每回合|每回合同名最多1次/.test(txt)&&s.nameUses[card.id])return false;if(card.effects.some(e=>!availableCost(ctx,e)))return false;const custom=hooks.canPlay?.(card,ctx);return custom!==false;}
 function estimateEffect(ctx,e){const {g,p,target:t}=ctx,A=stat(g,p,'attack'),D=stat(g,p,'defense');if(e.condition){const needsActual=/命中|实际|本卡确实/.test(e.condition);if(!needsActual){try{if(!condition(e.condition,{...ctx,preview:true}))return 0;}catch{/* Optional status helper: fall back to the stored status list. */}}}const sf=1+.1*((ctx.card.star||p.star||1)-1),n=((e.flat||0)+(e.atk||0)*A+(e.def||0)*D)*sf+(e.maxHp||0)*p.maxHp;const scale=['all_enemies','all_allies'].includes(e.target)?Math.min(2,e.target==='all_enemies'?g.enemies.filter(alive).length:g.allies.filter(alive).length):1;switch(e.kind){
 case'damage':{let m=1;if(e.perResource)m=Math.min(e.max||6,p.resources[e.perResource]||0);if(e.perDebuffType)m=Math.min(e.max||3,badTypes(t||{}));if(e.perDestroyedSummon)m=Math.min(2,pets(g).length);if(e.perDiscardedCard)m=Math.min(4,ctx.card.id==='mg_flying_cards'&&g.options?.patch?.smartFlying?flyingCandidates(ctx).length:handCandidates(ctx).length);if(e.perRemovedBlank)m=p.hand.filter(isBlank).length;return n*m*scale*(e.crit===false?1:1+stat(g,p,'crit')/100*stat(g,p,'critDamage')/100)*(100+5*p.level)/(100+5*p.level+stat(g,t||p,'defense'));}
 case'dot':{const group=e.target==='all_enemies'?g.enemies.filter(alive):[t].filter(Boolean),groupScale=group.length>2?2/group.length:1;let total=0;for(const foe of group){const room=Math.max(0,2-(p.flags.dotApplications?.[g.round+':'+foe.id]||0));if(!room)continue;const count=Math.min(e.stacks||1,room);const name=e.canonicalStatus||e.status,known=Object.entries(aliases).find(([k,v])=>k===name||v.includes(name)),names=known?[known[0],...known[1]]:[name];const existing=(foe.dots||[]).filter(z=>names.includes(z.canonicalStatus||z.status)||names.includes(z.status)).map(z=>({v:z.snapshotDamage??(z.atk||0)*A,r:z.remaining??2}));const power=(e.atk||0)*A*sf*groupScale;let delta=0;for(let i=0;i<count;i++){if(existing.length<3){existing.push({v:power,r:2});delta+=2*power;}else{existing.sort((a,b)=>a.v-b.v);if(power>existing[0].v){delta+=2*power-existing[0].v*existing[0].r;existing[0]={v:power,r:2};}}}const chance=clamp((e.baseChance??100)/100*(1+stat(g,p,'ehr')/100)*(1-stat(g,foe,'res')/100),0,1),K=100+5*p.level;total+=Math.max(0,delta)*K/(K+stat(g,foe,'defense'))*chance*.8;}return total;}
 case'heal':{const value=Math.min(n*(e.ticks||1)*scale,p.maxHp-p.hp)*((p.hp/p.maxHp)<.45?2.7:1.2);if(p.profession==='priest'&&g.options?.patch?.smartPriest){const remaining=Math.max(0,30+.8*A-(p.flags.other?.overflowUsed||0)),overflow=e.ticks||e.overTime?0:Math.min(remaining,Math.max(0,n*scale-(p.maxHp-p.hp))*.5),K=100+5*p.level;return value+overflow*K/(K+stat(g,t||p,'defense'));}return value+(p.profession==='priest'?n*.2:0);}
 case'shield':{const incoming=g.expectedIncoming??g.enemies.filter(alive).reduce((v,a)=>v+stat(g,a,'attack')*1.5,0);return Math.min(n*scale,Math.max(0,incoming*1.1-p.shield))*((p.hp/p.maxHp)<.45?2:1.1);}
 case'draw':return Math.min(Number(e.amount??e.value),6-state(g).extraDraw)*A*.16*(p.ap>3?1.4:.5);
 case'resource':return ((e.consume||Number(e.amount)<0)?0:Number(e.amount??e.value)||0)*A*.1;
 case'debuff':return scoreEffects(g,ctx.source??p,[e],t,{star:ctx.card.star});
 case'buff':return specialBuff(e)?A*.25*(has(p,e.canonicalStatus||e.status)?.05:1):scoreEffects(g,ctx.source??p,[e],t,{star:ctx.card.star});
 case'summon':return A*(pets(g).length<2?1.05:.25);
 case'chant':return (e.effects||[]).reduce((z,a)=>z+estimateEffect(ctx,a),0)*.8;
 case'utility':case'cleanse':case'dispel':{const action=e.action||e.kind;if(/cleanse|净化/.test(action))return scoreEffects(g,ctx.source??p,[{...e,kind:'cleanse',target:e.target??'self'}],t);if(action==='dispel')return scoreEffects(g,ctx.source??p,[{...e,kind:'dispel'}],t);if(action==='generate_blank'||action==='blank_regen')return A*.2;if(action==='discover')return A*.7;if(action==='bribe'||action==='escape_after_enemy_phase')return -1e6;return A*.07;}
 default:return 0;}}
 function scoreCard(g,card,target=g.enemies.find(alive)){if(card.id==='mg_flying_cards'&&g.options?.patch?.smartFlying&&!flyingCandidates(makeContext(g,card,target)).length)return -1e6;target=resolveCardTarget(g,card,target);const ctx=makeContext(g,card,target);ctx.preview=true;let v=card.effects.reduce((n,e)=>n+estimateEffect(ctx,e),0);v/=Math.max(.7,price(g,card));if(card.effects.some(e=>e.kind==='utility'&&/self_cost|自损/.test(e.action))&&g.player.hp/g.player.maxHp<.35)v*=.2;const custom=hooks.scoreCard?.(card,ctx,v);return Number.isFinite(custom)?custom:v;}
 function specialBonus(ctx){const p=ctx.p,s=state(ctx.g),attack=ctx.effects.some(e=>e.kind==='damage');if(!attack)return;for(const b of p.buffs||[]){if(!specialBuff(b)||b.charges===0)continue;let applicable=/下张攻击|下一张直接法术|下一张雷系直接|下张.*直接|下一次.*伤害提高/.test(b.status||'');if(/雷系/.test(b.status)&&ctx.card.profession!=='thunder_mage')applicable=false;if(/法术/.test(b.status)&&!['spell','attack'].includes(ctx.card.type))applicable=false;if(applicable){let v=b.valueUnit==='ratio'||Math.abs(b.value)<1?b.value:b.value/100;if(/速度命中补正/.test(b.status))ctx.options.hitBonus=(ctx.options.hitBonus||0)+v;else ctx.directBonus+=v;if(b.charges)b.charges--;}}
 if(s.nextAttackFlat?.charges>0&&s.nextAttackFlat.expires>=ctx.g.round){ctx.damageAdd.flat+=s.nextAttackFlat.flat;ctx.damageAdd.atk+=s.nextAttackFlat.atk;s.nextAttackFlat.charges--;ctx.disableCombo=true;}}
 function playCard(g,card,target=g.enemies.find(alive)){target=resolveCardTarget(g,card,target);if(!canPlay(g,card,target))throw Error(`ILLEGAL_CARD ${card.id}`);const p=g.player,s=state(g),ctx=makeContext(g,card,target);g.beginAction?.(p,card);ctx.paidAP=price(g,card,true,target);p.ap-=ctx.paidAP;const index=p.hand.findIndex(c=>c.uid===card.uid);if(index>=0)p.hand.splice(index,1);s.used[card.uid||card.id]=g.round;s.battleUses[card.id]=(s.battleUses[card.id]||0)+1;s.nameUses[card.id]=(s.nameUses[card.id]||0)+1;
 function expand(es){return es.flatMap(e=>e.kind==='conditional'&&(e.phase==='preResolve'||e.conditionTiming==='preResolve')?(condition(e.condition,ctx)?expand(e.effects):[]):[e]);}ctx.effects=expand(ctx.effects);
 const costs=ctx.effects.filter(e=>isCost(e)&&e.kind==='resource'||e.kind==='hp_cost'||e.action==='self_cost'||e.action==='自损生命'||e.action==='consume_all_resource');for(const e of costs)resolve(ctx,e);
 for(const e of ctx.effects.filter(e=>e.kind==='damage'&&e.consume)){const n=Math.min(p.resources[e.perResource]||0,e.max||Infinity);resource(ctx,e.perResource,-n);}
 const pre=ctx.effects.filter(e=>!costs.includes(e)&&(isCost(e)||e.kind==='utility'&&['shield_conversion','enemy_shield_bonus'].includes(e.action)||e.kind==='utility'&&/总量上限|总倍率上限/.test(e.action||'')));for(const e of pre)resolve(ctx,e);
 hooks.onBeforePlay?.(ctx);specialBonus(ctx);
 // Merge conditional same-hit additions into their preceding main damage before physics.
 const normal=ctx.effects.filter(e=>!costs.includes(e)&&!pre.includes(e));for(let i=0;i<normal.length;i++){const e=normal[i];if(e.mergeWithFirst){let prior=normal.slice(0,i).find(z=>z.kind==='damage'&&!z.mergeWithFirst);if(prior&&(!e.condition||condition(e.condition,{...ctx,preview:true}))){let count=e.perDebuffType?Math.min(e.max||3,badTypes(target)):e.perResource?ctx.spent[e.perResource]||0:1;prior.flat=(prior.flat||0)+(e.flat||0)*count;prior.atk=(prior.atk||0)+(e.atk||0)*count;}e._merged=true;}}
 for(const e of normal){if(e._merged)continue;resolve(ctx,e);}hooks.onAfterPlay?.(ctx);if(card.type==='defense'||ctx.totals.shield>0)p.thisTurn.defenseAP=(p.thisTurn.defenseAP??0)+ctx.paidAP;s.lastCard=card.id;s.cardsPlayed++;s.apSpent+=ctx.paidAP;const dead=p.hp<=0;if(ctx.exhaust||/消耗：本场|使用后消耗|使用后移除|本场移出循环/.test(limitsText(card))||card.id==='cm_quick_scan')p.exhaust.push(card);else p.discard.push(card);log(g,'play_card',{card:card.id,ap:ctx.paidAP,round:g.round,totals:ctx.totals,dead});return ctx;
 }
 ctrl.init=(g,profession,deckCards)=>{const p=g.player;p.profession=typeof profession==='string'?profession:profession.id;p.flags??={};p.resources??={};p.buffs??=[];p.debuffs??=[];p.dots??=[];p.hand=[];p.discard=[];p.exhaust=[];p.handLimit=p.handLimit||10;const catalog=g.cardCatalog instanceof Map?g.cardCatalog:new Map((g.cardCatalog||g.catalog?.cards||deckCards).map(c=>[c.id,c]));p.flags.pc={uid:0,used:{},battleUses:{},nameUses:{},extraDraw:0,extraAP:0,resourceCaps:{},resourceRoundCaps:{},gained:{},selfPaid:0,cardsPlayed:0,apSpent:0,discounts:[],triggers:[],regens:[],slotActions:{},catalog,generatedDiscovery:0,discoveriesThisTurn:0};const s=state(g);p.deck=shuffled(deckCards.map(c=>({...clone(c),uid:++s.uid,star:c.star||p.star||1})),g.rng);hooks.onInit?.(makeContext(g));draw(g,5,false);g.playerController=ctrl;return p;};
 ctrl.startTurn=g=>{const p=g.player,s=state(g);s.extraDraw=0;s.extraAP=0;s.gained={};s.selfPaid=0;s.nameUses={};s.cardsPlayed=0;s.apSpent=0;s.discoveriesThisTurn=0;s.discounts=s.discounts.filter(d=>d.expires>=g.round&&d.charges>0);p.ap=p.apMax||5;s.resourceCaps={...s.resourceCaps,...p.resourceCaps};const ctx=makeContext(g);const due=s.regens.filter(r=>r.next<=g.round&&r.remaining>0),strongest=new Map();for(const r of due){const prev=strongest.get(r.group);if(!prev||r.effect.flat>prev.effect.flat)strongest.set(r.group,r);}for(const r of strongest.values()){const owner=g.allies.find(a=>a.id===r.sourceId),dest=g.allies.find(a=>a.id===r.targetId);if(alive(owner)&&alive(dest)){const rc=makeContext(g,r.card,dest);rc.scheduled=true;resolve(rc,r.effect,dest,r.snapshot);}}for(const r of due){r.remaining--;r.next++;}s.regens=s.regens.filter(x=>x.remaining>0);if(s.blankRegen?.remaining>0&&s.blankRegen.next<=g.round){generateBlank(ctx,1);s.blankRegen.remaining--;s.blankRegen.next++;}if(g.round>1)draw(g,p.drawCount||3,false);hooks.onStartTurn?.(ctx);return ctx;};
 function summonAction(g,pet){const s=state(g);if(!alive(pet)||s.slotActions[pet.slot]===g.round)return;const ctx=makeContext(g,{id:`summon:${pet.name}`,name:pet.name,ap:0,effects:[],star:pet.star},g.enemies.find(alive));ctx.source=pet;ctx.summon=pet;ctx.isSummonAction=true;let skill;const cmd=pet.flags.mageCommand;if(pet.ruleSummon){s.slotActions[pet.slot]=g.round;pet.lastActionRound=g.round;g.beginPhase?.(pet);g.endPhase?.(pet);log(g,'summon_action',{pet:pet.name,skill:pet.ruleSummon.name,totals:ctx.totals});return;}if(cmd&&cmd.round<=g.round&&(cmd.expires===undefined||cmd.expires>=g.round)){skill={name:'指令',effects:cmd.effects};delete pet.flags.mageCommand;}else if(hooks.selectSummonSkill)skill=hooks.selectSummonSkill(ctx,pet);else{skill=pet.skills.filter(k=>!k.condition||k.condition==='默认'||k.condition==='否则'||condition(k.condition,ctx)).map(k=>({skill:k,value:(bestSkillTarget(g,pet,k)?.value??0)+(k.effects.some(e=>!['damage','heal','shield','buff','debuff','dot','cleanse','dispel'].includes(e.kind))?stat(g,pet,'attack')*.3:0)})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value)[0]?.skill;}if(!skill){s.slotActions[pet.slot]=g.round;return;}s.slotActions[pet.slot]=g.round;pet.lastActionRound=g.round;const canAct=g.beginPhase?.(pet);if(canAct===false||pet.hp<=0||has(pet,"hard_control")){g.endPhase?.(pet);return;}if(!cmd){const tactical=bestSkillTarget(g,pet,skill);if(tactical)ctx.target=tactical.target;}g.beginAction?.(pet,skill);for(const e of skill.effects)resolve(ctx,e,ctx.target,pet);pet.flags.actions=(pet.flags.actions||0)+1;pet.flags.lastSkill=skill.name;hooks.onSummonAction?.(ctx,pet,skill);g.endPhase?.(pet);log(g,'summon_action',{pet:pet.name,skill:skill.name,totals:ctx.totals});}
 ctrl.endTurn=g=>{const ctx=makeContext(g);hooks.onEndTurn?.(ctx);for(const pet of pets(g).sort((a,b)=>a.slot-b.slot)){if(pet.expiresRound<=g.round){pet.hp=0;pet.expired=true;g.workshopProgramEvent?.('summon_removed',{sourceId:pet.ownerId,targetId:pet.id,reason:'expired'});continue;}summonAction(g,pet);}state(g).triggers=state(g).triggers.filter(t=>t.expires>g.round&&t.remaining>0);return ctx;};
 function fireTrigger(g,t,target){const source=g.allies.find(a=>a.id===t.sourceId);if(!alive(source)||!alive(target))return;const ctx=makeContext(g,t.card,target);ctx.source=source;ctx.triggered=true;ctx.options.secondary=true;t.remaining--;t.usedRound=g.round;for(const e of t.effects)resolve(ctx,e,target,source);}
 ctrl.beforeEnemyAction=(g,enemy,skill)=>{for(const t of state(g).triggers){if(t.kind==='beforeEnemyAction'&&t.remaining>0&&t.targetId===enemy.id&&t.expires>=g.round)fireTrigger(g,t,enemy);}hooks.beforeEnemyAction?.(makeContext(g),enemy,skill);};
 ctrl.afterIncomingDamage=(g,event)=>{if(!event.hit||event.target.side!=='player'||event.secondary)return;for(const t of state(g).triggers){if(t.kind==='afterIncomingDamage'&&t.sourceId===event.target.id&&t.remaining>0&&t.expires>=g.round&&(!t.perRound||t.usedRound!==g.round))fireTrigger(g,t,event.source);}hooks.afterIncomingDamage?.(makeContext(g),event);};
 ctrl.price=price;ctrl.canPlay=canPlay;ctrl.scoreCard=scoreCard;ctrl.playCard=playCard;ctrl.makeContext=makeContext;ctrl.executeSummonAction=summonAction;ctrl.draw=(g,n,extra=true)=>draw(g,n,extra);ctrl.condition=(g,text,card,target)=>condition(text,makeContext(g,card,target));return ctrl;
}
export function auditCards(cards){const kinds={},actions={},conditions={};for(const c of cards)for(const e of gather(c.effects)){kinds[e.kind]=(kinds[e.kind]||0)+1;if(e.action)actions[e.action]=(actions[e.action]||0)+1;if(e.condition)conditions[e.condition]=(conditions[e.condition]||0)+1;}return{cards:cards.length,kinds,actions,conditions};}
